# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
