# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0003_reviewer_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='is_staff',
        ),
    ]
